CREATE TABLE IF NOT EXISTS "groups" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "workspace_id" integer NOT NULL,      -- FK
    "name" varchar(128) NOT NULL,
    "url" varchar(512) NOT NULL,
    "type" integer NOT NULL,
    "description" varchar(512) NOT NULL,
    "status" integer NOT NULL,
    "group_stat_id" integer,              -- FK
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("workspace_id", "id"),
    UNIQUE ("workspace_id", "name")
)
;

ALTER TABLE "groups" ADD CONSTRAINT "fk_groups_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id");
