[package]
name = "aether"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]
edition = "2021"
publish = false

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.2"
base64 = "0.21.5"
bytes = "1.5.0"
crypto-bigint = "0.5.4"
log = "0.4.20"
typenum = "1.17.0"
