[workspace]
members = [
    "optional_derive",
    "treblo",
    "treblo_cli",
    "aether",
    "aether_cli",
    "ichno",
    "ichno_cli",
    "ichnome",
    "ichnome_cli",
    "ichnome_web",
]
resolver = "2"
