CREATE TABLE IF NOT EXISTS "workspaces" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(128) NOT NULL,
    "description" varchar(512) NOT NULL,
    "status" integer NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("name")
)
;
