CREATE TABLE IF NOT EXISTS "attrs" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "workspace_id" integer NOT NULL,         -- FK
    "target_footprint_id" integer NOT NULL,  -- FK
    "target_digest" char(64) NOT NULL,       -- cached from footprint
    "key" varchar(128) NOT NULL,
    "value_footprint_id" integer NOT NULL,   -- FK
    "value_digest" char(64) NOT NULL,        -- cached from footprint
    "value_content_type" integer NOT NULL,
    "value_summary" varchar(512),
    "status" integer NOT NULL,
    "attr_stat_id" integer,                  -- FK
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE ("workspace_id", "target_footprint_id", "key")
)
;

ALTER TABLE "attrs" ADD CONSTRAINT "fk_attrs_workspace_id" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id");
ALTER TABLE "attrs" ADD CONSTRAINT "fk_attrs_target_footprint_id" FOREIGN KEY ("target_footprint_id") REFERENCES "footprints" ("id");
ALTER TABLE "attrs" ADD CONSTRAINT "fk_attrs_value_footprint_id" FOREIGN KEY ("value_footprint_id") REFERENCES "footprints" ("id");
ALTER TABLE "attrs" ADD CONSTRAINT "fk_attrs_attr_stat_id" FOREIGN KEY ("attr_stat_id") REFERENCES "stats" ("id");

CREATE INDEX "ix_attrs_workspace_id_updated_at" ON "attrs" ("workspace_id", "updated_at");
CREATE INDEX "ix_attrs_workspace_id_value_footprint_id_target_footprint_id_key" ON "attrs" ("workspace_id", "value_footprint_id", "target_footprint_id", "key");
CREATE INDEX "ix_attrs_workspace_id_value_summary_target_footprint_id_key" ON "attrs" ("workspace_id", "value_summary", "target_footprint_id", "key");
