[package]
name = "optional_derive"
version = "0.1.0"
authors = ["taskie <t@skie.jp>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.10.2"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = "1.0.35"
